[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "exercise_3"
version = "0.1"
dependencies = ["numpy"]

[tool.hatch.build.targets.wheel]
packages = ["polynomials", "shape"]